# The dataset contains transactions made by credit cards in September 2013 by European cardholders.
This dataset presents transactions that occurred in two days, where we have 492 frauds out of 284,807 transactions. The dataset is highly unbalanced, the positive class (frauds) account for 0.172% of all transactions.

It contains only numerical input variables which are the result of a PCA transformation. Unfortunately, due to confidentiality issues, we cannot provide the original features and more background information about the data. Features V1, V2, â€¦ V28 are the principal components obtained with PCA, the only features which have not been transformed with PCA are 'Time' and 'Amount'. Feature 'Time' contains the seconds elapsed between each transaction and the first transaction in the dataset. The feature 'Amount' is the transaction Amount, this feature can be used for example-dependant cost-sensitive learning. Feature 'Class' is the response variable and it takes value 1 in case of fraud and 0 otherwise.

# Importing the Required Libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
credit_card_data = pd.read_csv('/content/creditcard.csv')

In [ ]:
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [ ]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
49605,44132,-1.211298,-0.450385,1.440502,0.354908,-0.408886,1.636777,-0.951234,1.185703,-1.020024,...,0.086607,0.526001,0.191522,-1.026321,-0.529712,-0.057442,0.125643,0.000680,79.00,0.0
49606,44132,1.176642,0.154754,0.246080,0.800814,-0.590838,-1.487705,0.336949,-0.316725,-0.047056,...,-0.008572,-0.105115,-0.017629,0.937907,0.463495,0.332980,-0.062039,0.016149,40.00,0.0
49607,44133,-1.103844,0.186527,1.568397,1.307678,0.316942,0.290415,1.147621,-0.222930,0.000022,...,-0.160645,0.468407,0.389831,0.213000,-0.015877,-0.278962,0.322504,-0.270168,108.00,0.0
49608,44134,-0.262018,0.851831,1.459865,1.057694,-0.725526,0.274325,1.750817,-1.097029,0.439934,...,-0.272138,0.032569,-0.141121,0.476174,-0.587678,0.288669,-0.914934,-0.676786,172.82,0.0
49609,44135,-4.719790,-4.249875,1.850000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# dataset informations
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49610 entries, 0 to 49609
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    49610 non-null  int64
 1   V1      49610 non-null  float64
 2   V2      49610 non-null  float64
 3   V3      49610 non-null  float64
 4   V4      49609 non-null  float64
 5   V5      49609 non-null  float64
 6   V6      49609 non-null  float64
 7   V7      49609 non-null  float64
 8   V8      49609 non-null  float64
 9   V9      49609 non-null  float64
 10  V10     49609 non-null  float64
 11  V11     49609 non-null  float64
 12  V12     49609 non-null  float64
 13  V13     49609 non-null  float64
 14  V14     49609 non-null  float64
 15  V15     49609 non-null  float64
 16  V16     49609 non-null  float64
 17  V17     49609 non-null  float64
 18  V18     49609 non-null  float64
 19  V19     49609 non-null  float64
 20  V20     49609 non-null  float64
 21  V21     49609 non-null  float64
 22  V22     49609 non-null  float64
 23  V23     49609 non-null  float64
 24  V24     49609 non-null  float64
 25  V25     49609 non-null  float64
 26  V26     49609 non-null  float64
 27  V27     49609 non-null  float64
 28  V28     49609 non-null  float64
 29  Amount  49609 non-null  float64
 30  Class   49609 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 11.7 MB

In [ ]:
# checking the number of missing values in each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        1
V5        1
V6        1
V7        1
V8        1
V9        1
V10       1
V11       1
V12       1
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [ ]:
# distribution of legit transactions & fraudulent transactions
credit_card_data['Class'].value_counts()

0.0    49461
1.0      148
Name: Class, dtype: int64

This Dataset is highly unblanced

0 --> Normal Transaction

1 --> fraudulent transaction

In [ ]:
# separating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [ ]:
print(legit.shape)
print(fraud.shape)

(49461, 31)
(148, 31)

In [ ]:
# statistical measures of the data
legit.Amount.describe()

count    49461.000000
mean        93.099593
std        253.325102
min          0.000000
25%          7.680000
50%         25.000000
75%         85.000000
max      12910.930000
Name: Amount, dtype: float64

In [ ]:
fraud.Amount.describe()

count     148.000000
mean      100.170676
std       233.347471
min         0.000000
25%         1.000000
50%         9.560000
75%        99.990000
max      1809.680000
Name: Amount, dtype: float64

In [ ]:
# compare the values for both transactions
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,28809.010473,-0.220239,-0.003947,0.726173,0.167967,-0.240785,0.111250,-0.096470,0.042413,0.134593,...,0.046113,-0.031134,-0.106800,-0.039391,0.008275,0.135623,0.020410,0.003001,0.004455,93.099593
1.0,26877.182432,-7.675017,5.448919,-10.398242,5.939649,-5.681176,-2.280722,-8.068966,3.739332,-3.587074,...,0.470319,0.886835,-0.225326,-0.284732,-0.084733,0.246743,0.155479,0.603171,0.030658,100.170676

#Under-Sampling

Build a sample dataset containing similar distribution of normal transactions and Fraudulent Transactions

Number of Fraudulent Transactions --> 492

In [ ]:
legit_sample = legit.sample(n=492)

Concatenating two DataFrames

In [ ]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [ ]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
28006,34809,-2.108985,-0.269897,1.227404,1.755161,0.219572,0.263640,1.809891,-0.896658,-0.026287,...,-0.383096,0.578855,0.322608,0.157718,0.624757,-0.006501,-0.433701,-0.388009,198.20,0.0
30307,35864,-0.615123,1.093996,1.351516,0.753937,0.292207,-0.684219,1.360338,-0.646026,-0.054849,...,-0.023422,0.567256,-0.128604,0.410126,-0.161912,-0.379348,0.083305,-0.137194,46.80,0.0
21654,31794,1.199987,0.605182,-0.641530,1.024279,0.661337,-0.056164,0.113964,0.086561,-0.301211,...,-0.034110,-0.025129,-0.191114,-0.802986,0.678708,-0.272341,0.046753,0.036848,1.00,0.0
13198,23224,0.969471,0.370774,1.144937,2.669094,0.472665,1.965695,-0.541647,0.531607,0.986478,...,-0.389926,-0.596632,0.291498,-1.064150,-0.069401,-0.185429,0.065354,0.010112,0.00,0.0
4430,3769,1.347647,-0.772577,-0.946270,-1.593754,1.430855,3.284751,-1.133492,0.703140,0.356834,...,-0.261267,-0.912930,0.056743,0.921447,0.346823,-0.511346,-0.025182,0.020281,69.76,0.0

In [ ]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
46909,42985,-4.075975,0.963031,-5.076070,4.955963,-0.161437,-2.832663,-7.619765,1.618895,-2.992092,...,1.030738,0.165328,-1.017502,-0.477983,-0.304987,-0.106089,1.899714,0.511462,1.00,1.0
46918,42988,-4.423508,1.648048,-6.934388,4.894601,-5.078131,0.010849,-3.409096,1.409291,-3.260672,...,0.698359,0.487478,1.228698,-0.535217,0.388278,-0.009466,2.300164,0.081231,648.00,1.0
46998,43028,-1.109646,0.811069,-1.138135,0.935265,-2.330248,-0.116106,-1.621986,0.458028,-0.912189,...,0.641594,0.841755,0.176728,0.081004,-0.258899,0.707654,0.418649,0.080756,204.27,1.0
47802,43369,-3.365319,2.426503,-3.752227,0.276017,-2.305870,-1.961578,-3.029283,-1.674462,0.183961,...,2.070008,-0.512626,-0.248502,0.126550,0.104166,-1.055997,-1.200165,-1.012066,88.00,1.0
48094,43494,-1.278138,0.716242,-1.143279,0.217805,-1.293890,-1.168952,-2.564182,0.204532,-1.611155,...,0.490183,0.470427,-0.126261,-0.126644,-0.661908,-0.349793,0.454851,0.137843,24.90,1.0

In [ ]:
new_dataset['Class'].value_counts()

0.0    492
1.0    148
Name: Class, dtype: int64

In [ ]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,28936.144309,-0.124819,-0.084201,0.796229,0.117562,-0.245811,0.029404,-0.061084,0.081550,0.193920,...,0.072501,-0.065726,-0.104004,-0.043582,-0.012059,0.140737,0.026310,-0.000997,0.019952,93.798028
1.0,26877.182432,-7.675017,5.448919,-10.398242,5.939649,-5.681176,-2.280722,-8.068966,3.739332,-3.587074,...,0.470319,0.886835,-0.225326,-0.284732,-0.084733,0.246743,0.155479,0.603171,0.030658,100.170676

#Splitting the data into Features & Targets

In [ ]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [ ]:
print(X)

        Time        V1        V2        V3        V4        V5        V6  \
28006  34809 -2.108985 -0.269897  1.227404  1.755161  0.219572  0.263640
30307  35864 -0.615123  1.093996  1.351516  0.753937  0.292207 -0.684219
21654  31794  1.199987  0.605182 -0.641530  1.024279  0.661337 -0.056164
13198  23224  0.969471  0.370774  1.144937  2.669094  0.472665  1.965695
4430    3769  1.347647 -0.772577 -0.946270 -1.593754  1.430855  3.284751
...      ...       ...       ...       ...       ...       ...       ...
46909  42985 -4.075975  0.963031 -5.076070  4.955963 -0.161437 -2.832663
46918  42988 -4.423508  1.648048 -6.934388  4.894601 -5.078131  0.010849
46998  43028 -1.109646  0.811069 -1.138135  0.935265 -2.330248 -0.116106
47802  43369 -3.365319  2.426503 -3.752227  0.276017 -2.305870 -1.961578
48094  43494 -1.278138  0.716242 -1.143279  0.217805 -1.293890 -1.168952

             V7        V8        V9  ...       V20       V21       V22  \
28006  1.809891 -0.896658 -0.026287  ... -0.915496 -0.383096  0.578855
30307  1.360338 -0.646026 -0.054849  ...  0.379449 -0.023422  0.567256
21654  0.113964  0.086561 -0.301211  ... -0.098920 -0.034110 -0.025129
13198 -0.541647  0.531607  0.986478  ... -0.327742 -0.389926 -0.596632
4430  -1.133492  0.703140  0.356834  ...  0.278665 -0.261267 -0.912930
...         ...       ...       ...  ...       ...       ...       ...
46909 -7.619765  1.618895 -2.992092  ...  0.058861  1.030738  0.165328
46918 -3.409096  1.409291 -3.260672  ... -0.562264  0.698359  0.487478
46998 -1.621986  0.458028 -0.912189  ...  0.168891  0.641594  0.841755
47802 -3.029283 -1.674462  0.183961  ... -0.036837  2.070008 -0.512626
48094 -2.564182  0.204532 -1.611155  ...  0.817203  0.490183  0.470427

            V23       V24       V25       V26       V27       V28  Amount
28006  0.322608  0.157718  0.624757 -0.006501 -0.433701 -0.388009  198.20
30307 -0.128604  0.410126 -0.161912 -0.379348  0.083305 -0.137194   46.80
21654 -0.191114 -0.802986  0.678708 -0.272341  0.046753  0.036848    1.00
13198  0.291498 -1.064150 -0.069401 -0.185429  0.065354  0.010112    0.00
4430   0.056743  0.921447  0.346823 -0.511346 -0.025182  0.020281   69.76
...         ...       ...       ...       ...       ...       ...     ...
46909 -1.017502 -0.477983 -0.304987 -0.106089  1.899714  0.511462    1.00
46918  1.228698 -0.535217  0.388278 -0.009466  2.300164  0.081231  648.00
46998  0.176728  0.081004 -0.258899  0.707654  0.418649  0.080756  204.27
47802 -0.248502  0.126550  0.104166 -1.055997 -1.200165 -1.012066   88.00
48094 -0.126261 -0.126644 -0.661908 -0.349793  0.454851  0.137843   24.90

[640 rows x 30 columns]

In [ ]:
print(Y)

28006    0.0
30307    0.0
21654    0.0
13198    0.0
4430     0.0
        ...
46909    1.0
46918    1.0
46998    1.0
47802    1.0
48094    1.0
Name: Class, Length: 640, dtype: float64

# Split the data into Training data & Testing Data

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [ ]:
print(X.shape, X_train.shape, X_test.shape)

(640, 30) (512, 30) (128, 30)

#Model Training

#Logistic Regression

In [ ]:
model = LogisticRegression()

In [ ]:
# training the Logistic Regression Model with Training Data
model.fit(X_train, Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

#Model Evaluation

Accuracy Score

In [ ]:
# accuracy on training data
y_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(y_train_prediction, Y_train)

In [ ]:
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.978515625

In [ ]:
# accuracy on test data
y_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(y_test_prediction, Y_test)

In [ ]:
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.984375